/**
 * `storyFingerprint` — the app half of a value compared across the wire.
 *
 * Counterpart: `server/tests/ca-fingerprint-contract.test.ts`, which asserts
 * `headlineFingerprint` in `server/src/ca/select.ts` produces the SAME strings
 * from the SAME headlines. The table below is the contract; both files hold it.
 *
 * ## Why a table of literals and not a shared function
 *
 * The two packages are never compiled together, so there is nowhere to put one
 * implementation. Restating the expected output on both sides is the same
 * device `sse-contract.test.ts` uses for the wire format, for the same reason:
 * the only thing that can catch a one-sided change is a literal on each side.
 *
 * ## The failure this pair exists to prevent
 *
 * `selectItems` builds `new Set(request.seenFingerprints)` — values the DEVICE
 * computed — and tests its OWN freshly-computed fingerprint for membership. The
 * device was sending 64-bit hashes into a comparison against sorted word stems.
 * The sets could not intersect, and nothing failed:
 *
 *   - the server re-shortlisted a running story it had already delivered,
 *   - paid for a second note on it,
 *   - spent one of the six daily slots carrying it,
 *   - and the device dropped it on ingest as `duplicate_headline`.
 *
 * So she never saw a duplicate. She saw a five-item digest, every day, and a
 * larger bill — and the drop histogram blamed the device rather than naming the
 * broken comparison. A silent failure that costs money is worth two tests.
 */

import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import { headlineFingerprint, storyFingerprint } from '../src/lib/ca-map';

/**
 * Headline to fingerprint. Generated by RUNNING the server's implementation,
 * not by reading it — a table written by hand from the code would encode the
 * same misreading on both sides.
 */
const CONTRACT: readonly [string, string][] = [
  ['SC quashes the bonds scheme', 'bond-quash-scheme'],
  ['Bonds scheme quashed by SC', 'bond-quash-scheme'],
  ['Cabinet approves revised Forest Rights framework', 'approv-cabinet-forest-framework-revis-right'],
  ['RBI holds repo rate at 6.5% for the sixth time', 'hold-rate-rbi-repo-sixth-time'],
  ['Tribal affairs ministry notifies 3 new communities', 'affair-community-ministry-notify-tribal'],
  // The stemmer handles plural and tense, NOT irregular verbs. These two do not
  // collapse, and that is the documented trade — pinned so nobody "fixes" the
  // stemmer on one side only.
  ['SC strikes down electoral bonds', 'bond-down-electoral-strik'],
  ['Electoral bonds struck down by SC', 'bond-down-electoral-struck'],
  // Non-Latin script: `[^a-z0-9\s]` strips every character, so without the
  // fallback every Hindi headline would be "the same story" as every other.
  // PIB serves Hindi outright when its `reg` parameter is wrong.
  ['उच्चतम न्यायालय ने चुनावी बॉन्ड योजना रद्द की', 'उच्चतम न्यायालय ने चुनावी बॉन्ड योजना रद्द की'],
  ['', ''],
];

describe('storyFingerprint agrees with the server, headline for headline', () => {
  for (const [headline, expected] of CONTRACT) {
    it(`maps ${JSON.stringify(headline).slice(0, 52)} to ${JSON.stringify(expected).slice(0, 46)}`, () => {
      assert.equal(storyFingerprint(headline), expected);
    });
  }
});

describe('the two fingerprints answer different questions', () => {
  it('collapses a reworded headline, which the storage key deliberately does not', () => {
    // `storyFingerprint` asks "has she been shown this story?" and says yes.
    // `headlineFingerprint` asks "do I hold this row?" and says no. Both are
    // correct, which is why there are two of them.
    const a = 'SC quashes the bonds scheme';
    const b = 'Bonds scheme quashed by SC';
    assert.equal(storyFingerprint(a), storyFingerprint(b));
    assert.notEqual(headlineFingerprint(a), headlineFingerprint(b));
  });

  it('is never the storage key`s format', () => {
    // A regression that swapped one for the other would be invisible on the
    // device — the app never compares story fingerprints to anything locally.
    const fp = storyFingerprint('Cabinet approves revised Forest Rights framework');
    assert.doesNotMatch(fp, /^[0-9a-f]{16}$/, 'that is `headlineFingerprint`, not this');
    assert.match(fp, /^[a-z0-9-]+$/);
  });
});

describe('properties the server relies on', () => {
  it('is stable across repeated calls', () => {
    for (const [headline] of CONTRACT) {
      assert.equal(storyFingerprint(headline), storyFingerprint(headline));
    }
  });

  it('caps at eight stems, so a long headline cannot bloat the request', () => {
    const long = 'Parliament passes comprehensive amendment legislation reforming municipal '
      + 'governance financing structures across seventeen states territories nationwide';
    const fp = storyFingerprint(long);
    assert.ok(fp.split('-').length <= 8, `${fp} has more than eight stems`);
  });

  it('ignores word order, punctuation and case', () => {
    // Same words, rearranged. Deliberately NOT `holds`/`held`: the stemmer
    // leaves irregular verbs alone, so that pair would be testing the stemmer
    // rather than the sort, and it would fail.
    assert.equal(
      storyFingerprint('RBI holds repo rate at 6.5% for the sixth time'),
      storyFingerprint('sixth TIME: RBI holds repo rate, at 6.5%'),
    );
  });

  it('does not collapse two genuinely different stories', () => {
    assert.notEqual(
      storyFingerprint('RBI holds repo rate at 6.5%'),
      storyFingerprint('RBI cuts repo rate to 6.0%'),
    );
  });
});
